Home Page Animation
build-trust/ockam-website pull request #648
Opened 2022-10-28 05:34 UTC by m-ata

In this PR, I worked on the animation of home page.
For the animation, I created a generic `useTransition()` hook to handle the transition with duration, delay, child render, and items to be render.

2022-10-28 13:54 UTC, miedziak requested changes
Great start with animations !!! Just one major thing in comments. There is also an issue, since the requirements was to show animation only once the element appear on the screen ( no back animation when we ie, scroll up back )

2022-10-28 13:54 UTC, miedziak commented on src/hooks/useTransition.tsx
> +export default useTransition;
suggestion: quite a nice idea with this multi element approach, I like it. However, I have two problems with that:
- It forces us to put content as an array outside the jsx/render of our components.  Also, the item itself is outside. This is usually not the optimal way to deal with the components. For example in case one element from the list would be a different component 
- because of this list, sometimes you have to use separate useTransitions anyway (ie. Packages.tsx )

If we try to stick with this concept, I would rather try to make it as component instead of hook, and try to work for something like this in usage:
```
<Transition> 
  <Transition.Item><p>Some cool content</p></Transition.Item>
  <Transition.Item><p>Some cool content</p></Transition.Item>
  <Transition.Item><p>Some cool content</p></Transition.Item>
</Transition>
```
However, I'm also fine If we just create a component to animate one element, and just set delay for it. Simillar as we did in the old website version -> https://github.com/build-trust/ockam-website/blob/6a98931ced81b020b5c9d1ca48729c90dbd0b4a6/src/components/AnimateOnScroll.js

In this case, probably useSpring hook will be enough.

2022-10-31 08:13 UTC, m-ata commented on src/hooks/useTransition.tsx
> +export default useTransition;
Thank you for the suggestion. I thought that we need to show animation when the user scroll up again. I have converted `useTransition` to component and we have `useEffectOnce` hook to ensure that it will run only once.

2022-10-31 11:14 UTC, miedziak requested changes
Great improvements !!! Just two minors think and we are good to go !

2022-10-31 11:14 UTC, miedziak commented on src/components/Transition/Transition.tsx
> +      observer?.observe(ref.current as Element);
question/todo: Shouldn't we destroy this observer when unmount the component ?

2022-10-31 11:14 UTC, miedziak commented on package.json
> +    "react-spring": "^9.5.5",
todo: please target direct version

2022-11-01 15:14 UTC, m-ata commented on package.json
> +    "react-spring": "^9.5.5",
Fixed!

2022-11-07 15:57 UTC, miedziak approved these changes

2022-11-07 16:06 UTC, merged