feat: implemented style guide sections
build-trust/ockam-website pull request #664
Opened 2022-11-08 23:18 UTC by m-ata

In this PR, I have developed style guide sections

2022-11-09 16:01 UTC, miedziak commented on src/utils/copyTextToClipboard.ts
> +async function copyTextToClipboard(
suggestion: should this be a hook ? We wouldn't need local state thanks to that.

2022-11-09 16:06 UTC, miedziak commented on src/views/style-guide/components/ColorCard.tsx
> +              key={element + i.toString()}
nitpick/question: is this `i.toString()` necessary ? Same in other places

2022-11-09 16:13 UTC, miedziak commented on src/views/style-guide/components/GraphicsCard.tsx
> +        </Menu>
suggestion: seems like we reuse this button with menu also in other section, maybe it's worth creating some reusable component for that ? We can live that for later as an improvement, but you should take care of that.

2022-11-09 16:14 UTC, miedziak commented on src/views/style-guide/components/LogoCard.tsx
> +                      _checked={{ borderWidth: '4px ', borderColor: 'avocado.600' }}
nitpick: as I mention previously, let's keep default checked state, no need to put custom styles here

2022-11-09 16:15 UTC, miedziak commented on src/views/style-guide/components/TeamPhotoSample.tsx
> +        alt="Dan Abramov"
:)

2022-11-09 22:09 UTC, m-ata commented on src/views/style-guide/components/GraphicsCard.tsx
> +        </Menu>
Thanks for the suggestion. I've applied it.

2022-11-09 22:15 UTC, m-ata commented on src/consts/graphics.ts
> +const graphics = [
Done!

2022-11-09 22:16 UTC, m-ata commented on src/utils/copyTextToClipboard.ts
> +async function copyTextToClipboard(
Well, I don't think so we need hook here as it is just a simple functionality and you know we don't need any state or specific react related thing that's why I create as a normal utils function instead of custom hook

2022-11-09 22:28 UTC, m-ata commented on src/typings/StyleGuide.ts
> +};
Good idea. It's done now!

2022-11-10 18:13 UTC, m-ata commented on src/views/style-guide/components/LogoCard.tsx
> +                      _checked={{ borderWidth: '4px ', borderColor: 'avocado.600' }}
Now it's done!

2022-11-10 19:03 UTC, m-ata commented on src/views/style-guide/components/ColorCard.tsx
> +              key={element + i.toString()}
ok I wrapped it with template literal because we have some linting rule that `index` can't be directly used as `key`

2022-11-11 23:16 UTC, m-ata commented on src/views/style-guide/IconsSection.tsx
> +        </Box>
- The reason of putting images in `public` folder is it will not be the part of our bundle which results the bundle light as compared to if we put it in the `src/assets`.
- Yes, you are right. I have changed it and rendering pngs.
- Now, I have used Next Image where it is needed.

2022-11-14 10:50 UTC, miedziak requested changes
you have unnecessary make icons as png. Don't you want to make this icons folder dynamic as I have mentioned?

2022-11-14 10:50 UTC, miedziak commented on src/views/style-guide/IconsSection.tsx
> +        </Box>
regarding this public folder, I'm not sure about if this will make any savings in bundle, assets in bundle are external files anyway. How it makes the bundle lighter?

2022-11-15 11:47 UTC, miedziak requested changes

2022-11-15 11:47 UTC, miedziak commented on src/api/mdxApi.js
> +export const getIconsNames = async () => {
todo: let's move 'getIconsNames', 'styleGuideFilePaths'  and  'iconSectionPaths' to separate file, like 'styleGuideApi' to keep it separate by resources.

2022-11-16 10:19 UTC, miedziak approved these changes

2022-11-16 10:20 UTC, merged