Numeric Animation
build-trust/ockam-website pull request #668
Opened 2022-11-16 10:51 UTC by m-ata

2022-11-17 15:33 UTC, miedziak requested changes
GJ, just some minor things

2022-11-17 15:33 UTC, miedziak commented on src/components/NumericAnimation/NumericAnimation.tsx
> +          >
todo: same here, we can use styled components here, you can probably do something like 
```js
const AnimatedContainer = styled(animated.div)`
...
`
```

2022-11-17 20:05 UTC, m-ata commented on src/components/NumericAnimation/NumericAnimation.tsx
> +              }}
done!

2022-11-17 20:05 UTC, m-ata commented on src/components/NumericAnimation/NumericAnimation.tsx
> +              fontSize: '120px',
done!

2022-11-17 22:33 UTC, m-ata commented on src/components/NumericAnimation/NumericAnimation.tsx
> +          >
Good suggestion. Implemented now.

2022-11-21 09:40 UTC, miedziak approved these changes

2022-11-21 10:19 UTC, merged