Next & Previous Blog Functionality
build-trust/ockam-website pull request #674
Opened 2022-11-30 21:54 UTC by m-ata

2022-12-01 12:53 UTC, miedziak requested changes

2022-12-01 12:53 UTC, miedziak commented on src/components/BlogsPagination.tsx
> +      {currentBlogIndex !== sortedLinearGroupedBlogs.length - 1 && (
nitpick: It would be nicer to read the code if you make this named variable:
```
const isNotLastPost = currentBlogIndex !== sortedLinearGroupedBlogs.length - 1;
```
same for for first

2022-12-03 23:03 UTC, m-ata commented on src/components/BlogsPagination.tsx
> +      {currentBlogIndex !== sortedLinearGroupedBlogs.length - 1 && (
Done !

2022-12-04 13:22 UTC, miedziak approved these changes
please squash and we are good to go

2022-12-04 13:22 UTC, miedziak commented on src/components/BlogsPagination.tsx
> +  const sortedLinearGroupedBlogs = useMemo(() => { // creating a sorted list of linear blogs
nitpick: comment should be above the function/variable

2022-12-04 22:52 UTC, m-ata commented on src/components/BlogsPagination.tsx
> +  const sortedLinearGroupedBlogs = useMemo(() => { // creating a sorted list of linear blogs
Done!

2022-12-05 09:11 UTC, merged