SEO
build-trust/ockam-website pull request #682
Opened 2023-01-02 21:35 UTC by m-ata

2023-01-03 10:14 UTC, miedziak requested changes

2023-01-03 10:14 UTC, miedziak commented on next.config.js
> +    },
todo: If you will get more and more 410 redirect, this flags like `isJobExpired` will start to be quite messy. I would suggest to create separate `410` files, one for docs redirects and second for 'team' redirects. So there will be: 
```jsx
    {
      source: '/posts/:slug*',
      destination: '/docs-410',
      permanent: true,
    },
...
    {
      source: '/team/Senior-Support-Engineer/914dd8e6-e94a-4a23-90db-d92d271d41e2',
      destination: '/jobs-410',
      permanent: true,
    },

```

2023-01-03 10:14 UTC, miedziak commented on next.config.js
> +    },
suggestion: I think you can group this job redirects to separate file and just extract it here, will be cleaner when reading this file:
```js
const nextConfig = {
  images: { formats: ['image/webp'] },
  redirects: async () => [
  ...
     {
      source: '/posts/:slug*',
      destination: '/410',
      permanent: true,
    },
  ...jobsRedirects,
  ]
```

2023-01-04 09:25 UTC, m-ata commented on next.config.js
> +    },
Done!

2023-01-04 09:26 UTC, m-ata commented on next.config.js
> +    },
Nice Idea. I implemented that way.

2023-01-04 11:15 UTC, miedziak requested changes

2023-01-04 11:15 UTC, miedziak commented on lib/utils.js
> +const redirectJobs = [
suggestion: utils sound more like a function purpose. I would instead go with just 'redirects.js'

2023-01-04 11:40 UTC, m-ata commented on lib/utils.js
> +const redirectJobs = [
fixed!

2023-01-04 11:41 UTC, miedziak approved these changes

2023-01-04 21:43 UTC, merged